version: '3'
services:
  mysql:
    image: daocloud.io/library/mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
  redis:
    image: daocloud.io/library/redis:latest
    ports:
      - 6379:6379
  consul:
    image: daocloud.io/library/consul:latest
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
