// Code generated by Kitex v0.9.1. DO NOT EDIT.

package echostream

import (
	"context"
	"errors"
	"fmt"
	pbapi "github.com/cloudwego/biz-demo/gomall/demo/demo_proto/kitex_gen/pbapi"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"EchoStream": kitex.NewMethodInfo(
		echoStreamHandler,
		newEchoStreamArgs,
		newEchoStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
}

var (
	echoStreamServiceInfo                = NewServiceInfo()
	echoStreamServiceInfoForClient       = NewServiceInfoForClient()
	echoStreamServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return echoStreamServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return echoStreamServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return echoStreamServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EchoStream"
	handlerType := (*pbapi.EchoStream)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "pbapi",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func echoStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &echoStreamEchoStreamServer{st}
	req := new(pbapi.Request)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(pbapi.EchoStream).EchoStream(req, stream)
}

type echoStreamEchoStreamClient struct {
	streaming.Stream
}

func (x *echoStreamEchoStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *echoStreamEchoStreamClient) Recv() (*pbapi.Response, error) {
	m := new(pbapi.Response)
	return m, x.Stream.RecvMsg(m)
}

type echoStreamEchoStreamServer struct {
	streaming.Stream
}

func (x *echoStreamEchoStreamServer) Send(m *pbapi.Response) error {
	return x.Stream.SendMsg(m)
}

func newEchoStreamArgs() interface{} {
	return &EchoStreamArgs{}
}

func newEchoStreamResult() interface{} {
	return &EchoStreamResult{}
}

type EchoStreamArgs struct {
	Req *pbapi.Request
}

func (p *EchoStreamArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(pbapi.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *EchoStreamArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *EchoStreamArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *EchoStreamArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EchoStreamArgs) Unmarshal(in []byte) error {
	msg := new(pbapi.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EchoStreamArgs_Req_DEFAULT *pbapi.Request

func (p *EchoStreamArgs) GetReq() *pbapi.Request {
	if !p.IsSetReq() {
		return EchoStreamArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EchoStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoStreamArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EchoStreamResult struct {
	Success *pbapi.Response
}

var EchoStreamResult_Success_DEFAULT *pbapi.Response

func (p *EchoStreamResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(pbapi.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *EchoStreamResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *EchoStreamResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *EchoStreamResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EchoStreamResult) Unmarshal(in []byte) error {
	msg := new(pbapi.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EchoStreamResult) GetSuccess() *pbapi.Response {
	if !p.IsSetSuccess() {
		return EchoStreamResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EchoStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*pbapi.Response)
}

func (p *EchoStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoStreamResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoStream(ctx context.Context, req *pbapi.Request) (EchoStream_EchoStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "EchoStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &echoStreamEchoStreamClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}
