// Code generated by Kitex v0.9.1. DO NOT EDIT.

package echobidirectionalstream

import (
	"context"
	"errors"
	"fmt"
	pbapi "github.com/cloudwego/biz-demo/gomall/demo/demo_proto/kitex_gen/pbapi"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"EchoBidirectionalStream": kitex.NewMethodInfo(
		echoBidirectionalStreamHandler,
		newEchoBidirectionalStreamArgs,
		newEchoBidirectionalStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingBidirectional),
	),
}

var (
	echoBidirectionalStreamServiceInfo                = NewServiceInfo()
	echoBidirectionalStreamServiceInfoForClient       = NewServiceInfoForClient()
	echoBidirectionalStreamServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return echoBidirectionalStreamServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return echoBidirectionalStreamServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return echoBidirectionalStreamServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EchoBidirectionalStream"
	handlerType := (*pbapi.EchoBidirectionalStream)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "pbapi",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func echoBidirectionalStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &echoBidirectionalStreamEchoBidirectionalStreamServer{st}
	return handler.(pbapi.EchoBidirectionalStream).EchoBidirectionalStream(stream)
}

type echoBidirectionalStreamEchoBidirectionalStreamClient struct {
	streaming.Stream
}

func (x *echoBidirectionalStreamEchoBidirectionalStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *echoBidirectionalStreamEchoBidirectionalStreamClient) Send(m *pbapi.Request) error {
	return x.Stream.SendMsg(m)
}
func (x *echoBidirectionalStreamEchoBidirectionalStreamClient) Recv() (*pbapi.Response, error) {
	m := new(pbapi.Response)
	return m, x.Stream.RecvMsg(m)
}

type echoBidirectionalStreamEchoBidirectionalStreamServer struct {
	streaming.Stream
}

func (x *echoBidirectionalStreamEchoBidirectionalStreamServer) Send(m *pbapi.Response) error {
	return x.Stream.SendMsg(m)
}

func (x *echoBidirectionalStreamEchoBidirectionalStreamServer) Recv() (*pbapi.Request, error) {
	m := new(pbapi.Request)
	return m, x.Stream.RecvMsg(m)
}

func newEchoBidirectionalStreamArgs() interface{} {
	return &EchoBidirectionalStreamArgs{}
}

func newEchoBidirectionalStreamResult() interface{} {
	return &EchoBidirectionalStreamResult{}
}

type EchoBidirectionalStreamArgs struct {
	Req *pbapi.Request
}

func (p *EchoBidirectionalStreamArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(pbapi.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *EchoBidirectionalStreamArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *EchoBidirectionalStreamArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *EchoBidirectionalStreamArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EchoBidirectionalStreamArgs) Unmarshal(in []byte) error {
	msg := new(pbapi.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EchoBidirectionalStreamArgs_Req_DEFAULT *pbapi.Request

func (p *EchoBidirectionalStreamArgs) GetReq() *pbapi.Request {
	if !p.IsSetReq() {
		return EchoBidirectionalStreamArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EchoBidirectionalStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoBidirectionalStreamArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EchoBidirectionalStreamResult struct {
	Success *pbapi.Response
}

var EchoBidirectionalStreamResult_Success_DEFAULT *pbapi.Response

func (p *EchoBidirectionalStreamResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(pbapi.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *EchoBidirectionalStreamResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *EchoBidirectionalStreamResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *EchoBidirectionalStreamResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EchoBidirectionalStreamResult) Unmarshal(in []byte) error {
	msg := new(pbapi.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EchoBidirectionalStreamResult) GetSuccess() *pbapi.Response {
	if !p.IsSetSuccess() {
		return EchoBidirectionalStreamResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EchoBidirectionalStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*pbapi.Response)
}

func (p *EchoBidirectionalStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoBidirectionalStreamResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoBidirectionalStream(ctx context.Context) (EchoBidirectionalStream_EchoBidirectionalStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "EchoBidirectionalStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &echoBidirectionalStreamEchoBidirectionalStreamClient{res.Stream}
	return stream, nil
}
