// Code generated by Kitex v0.9.1. DO NOT EDIT.

package echoclientstream

import (
	"context"
	"errors"
	"fmt"
	pbapi "github.com/cloudwego/biz-demo/gomall/demo/demo_proto/kitex_gen/pbapi"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"EchoClientStream": kitex.NewMethodInfo(
		echoClientStreamHandler,
		newEchoClientStreamArgs,
		newEchoClientStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingClient),
	),
}

var (
	echoClientStreamServiceInfo                = NewServiceInfo()
	echoClientStreamServiceInfoForClient       = NewServiceInfoForClient()
	echoClientStreamServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return echoClientStreamServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return echoClientStreamServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return echoClientStreamServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EchoClientStream"
	handlerType := (*pbapi.EchoClientStream)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "pbapi",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func echoClientStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &echoClientStreamEchoClientStreamServer{st}
	return handler.(pbapi.EchoClientStream).EchoClientStream(stream)
}

type echoClientStreamEchoClientStreamClient struct {
	streaming.Stream
}

func (x *echoClientStreamEchoClientStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *echoClientStreamEchoClientStreamClient) Send(m *pbapi.Request) error {
	return x.Stream.SendMsg(m)
}
func (x *echoClientStreamEchoClientStreamClient) CloseAndRecv() (*pbapi.Response, error) {
	if err := x.Stream.Close(); err != nil {
		return nil, err
	}
	m := new(pbapi.Response)
	return m, x.Stream.RecvMsg(m)
}

type echoClientStreamEchoClientStreamServer struct {
	streaming.Stream
}

func (x *echoClientStreamEchoClientStreamServer) SendAndClose(m *pbapi.Response) error {
	return x.Stream.SendMsg(m)
}

func (x *echoClientStreamEchoClientStreamServer) Recv() (*pbapi.Request, error) {
	m := new(pbapi.Request)
	return m, x.Stream.RecvMsg(m)
}

func newEchoClientStreamArgs() interface{} {
	return &EchoClientStreamArgs{}
}

func newEchoClientStreamResult() interface{} {
	return &EchoClientStreamResult{}
}

type EchoClientStreamArgs struct {
	Req *pbapi.Request
}

func (p *EchoClientStreamArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(pbapi.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *EchoClientStreamArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *EchoClientStreamArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *EchoClientStreamArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EchoClientStreamArgs) Unmarshal(in []byte) error {
	msg := new(pbapi.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EchoClientStreamArgs_Req_DEFAULT *pbapi.Request

func (p *EchoClientStreamArgs) GetReq() *pbapi.Request {
	if !p.IsSetReq() {
		return EchoClientStreamArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EchoClientStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoClientStreamArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EchoClientStreamResult struct {
	Success *pbapi.Response
}

var EchoClientStreamResult_Success_DEFAULT *pbapi.Response

func (p *EchoClientStreamResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(pbapi.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *EchoClientStreamResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *EchoClientStreamResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *EchoClientStreamResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EchoClientStreamResult) Unmarshal(in []byte) error {
	msg := new(pbapi.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EchoClientStreamResult) GetSuccess() *pbapi.Response {
	if !p.IsSetSuccess() {
		return EchoClientStreamResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EchoClientStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*pbapi.Response)
}

func (p *EchoClientStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoClientStreamResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoClientStream(ctx context.Context) (EchoClientStream_EchoClientStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "EchoClientStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &echoClientStreamEchoClientStreamClient{res.Stream}
	return stream, nil
}
